/*
 * Transactional API
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EmailValidatorResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-25T18:25:48.901062+01:00[Europe/Lisbon]")
public class EmailValidatorResponse {
  @SerializedName("emailValid")
  private String emailValid = null;

  @SerializedName("emailTemporary")
  private String emailTemporary = null;

  @SerializedName("mx")
  private String mx = null;

  public EmailValidatorResponse emailValid(String emailValid) {
    this.emailValid = emailValid;
    return this;
  }

   /**
   * Email Validation Flag
   * @return emailValid
  **/
  @Schema(example = "true", description = "Email Validation Flag")
  public String getEmailValid() {
    return emailValid;
  }

  public void setEmailValid(String emailValid) {
    this.emailValid = emailValid;
  }

  public EmailValidatorResponse emailTemporary(String emailTemporary) {
    this.emailTemporary = emailTemporary;
    return this;
  }

   /**
   * Temporary Email Validation
   * @return emailTemporary
  **/
  @Schema(example = "true", description = "Temporary Email Validation")
  public String getEmailTemporary() {
    return emailTemporary;
  }

  public void setEmailTemporary(String emailTemporary) {
    this.emailTemporary = emailTemporary;
  }

  public EmailValidatorResponse mx(String mx) {
    this.mx = mx;
    return this;
  }

   /**
   * Temporary Email Validation
   * @return mx
  **/
  @Schema(example = "true", description = "Temporary Email Validation")
  public String getMx() {
    return mx;
  }

  public void setMx(String mx) {
    this.mx = mx;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailValidatorResponse emailValidatorResponse = (EmailValidatorResponse) o;
    return Objects.equals(this.emailValid, emailValidatorResponse.emailValid) &&
        Objects.equals(this.emailTemporary, emailValidatorResponse.emailTemporary) &&
        Objects.equals(this.mx, emailValidatorResponse.mx);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailValid, emailTemporary, mx);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailValidatorResponse {\n");
    
    sb.append("    emailValid: ").append(toIndentedString(emailValid)).append("\n");
    sb.append("    emailTemporary: ").append(toIndentedString(emailTemporary)).append("\n");
    sb.append("    mx: ").append(toIndentedString(mx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
