/*
 * Transactional API
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SenderMultiChannelObject;
import io.swagger.client.model.ToMultiChannelObject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ExecuteMultiChannelRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-25T18:25:48.901062+01:00[Europe/Lisbon]")
public class ExecuteMultiChannelRequest {
  @SerializedName("templateId")
  private String templateId = null;

  @SerializedName("to")
  private ToMultiChannelObject to = null;

  @SerializedName("sender")
  private SenderMultiChannelObject sender = null;

  public ExecuteMultiChannelRequest templateId(String templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * the id of the Multi Channel Template to be used.
   * @return templateId
  **/
  @Schema(example = "1234", required = true, description = "the id of the Multi Channel Template to be used.")
  public String getTemplateId() {
    return templateId;
  }

  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public ExecuteMultiChannelRequest to(ToMultiChannelObject to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @Schema(description = "")
  public ToMultiChannelObject getTo() {
    return to;
  }

  public void setTo(ToMultiChannelObject to) {
    this.to = to;
  }

  public ExecuteMultiChannelRequest sender(SenderMultiChannelObject sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  @Schema(description = "")
  public SenderMultiChannelObject getSender() {
    return sender;
  }

  public void setSender(SenderMultiChannelObject sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteMultiChannelRequest executeMultiChannelRequest = (ExecuteMultiChannelRequest) o;
    return Objects.equals(this.templateId, executeMultiChannelRequest.templateId) &&
        Objects.equals(this.to, executeMultiChannelRequest.to) &&
        Objects.equals(this.sender, executeMultiChannelRequest.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, to, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteMultiChannelRequest {\n");
    
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
