/*
 * Transactional API
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ManualPush
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-25T18:20:46.782806+01:00[Europe/Lisbon]")
public class ManualPush {
  @SerializedName("to")
  private String to = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("textBody")
  private String textBody = null;

  @SerializedName("appId")
  private Integer appId = null;

  @SerializedName("custom")
  private String custom = null;

  public ManualPush to(String to) {
    this.to = to;
    return this;
  }

   /**
   * The contact of the recipient. format should be countryCode-phoneNumber.
   * @return to
  **/
  @Schema(example = "1234", required = true, description = "The contact of the recipient. format should be countryCode-phoneNumber.")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public ManualPush subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * The subject of the message.
   * @return subject
  **/
  @Schema(example = "Hello World", required = true, description = "The subject of the message.")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public ManualPush textBody(String textBody) {
    this.textBody = textBody;
    return this;
  }

   /**
   * The body of the message.
   * @return textBody
  **/
  @Schema(example = "This is an Hello to the World", required = true, description = "The body of the message.")
  public String getTextBody() {
    return textBody;
  }

  public void setTextBody(String textBody) {
    this.textBody = textBody;
  }

  public ManualPush appId(Integer appId) {
    this.appId = appId;
    return this;
  }

   /**
   * The id of the application. Should be previously configured in the system.
   * @return appId
  **/
  @Schema(example = "1234", required = true, description = "The id of the application. Should be previously configured in the system.")
  public Integer getAppId() {
    return appId;
  }

  public void setAppId(Integer appId) {
    this.appId = appId;
  }

  public ManualPush custom(String custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Any custom information to associate the message with.
   * @return custom
  **/
  @Schema(example = "This os for a test", description = "Any custom information to associate the message with.")
  public String getCustom() {
    return custom;
  }

  public void setCustom(String custom) {
    this.custom = custom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManualPush manualPush = (ManualPush) o;
    return Objects.equals(this.to, manualPush.to) &&
        Objects.equals(this.subject, manualPush.subject) &&
        Objects.equals(this.textBody, manualPush.textBody) &&
        Objects.equals(this.appId, manualPush.appId) &&
        Objects.equals(this.custom, manualPush.custom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, subject, textBody, appId, custom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManualPush {\n");
    
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    textBody: ").append(toIndentedString(textBody)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
